### ISSUE TITLE
practicas

### ISSUE THREAD

**Issue by grupohernandezalba** [rodri-dot-git/sistemas-geo#2]
Excelente @rodri-dot-git muy buen trabajo , me gusto la funcionalidad y el diseño.
Cuida los acentos, que no se te pase, Google considera como factor la correcta escritura en el SEO. Checalo.
![Captura de Pantalla 2020-03-01 a la(s) 12 12 06](https://user-images.githubusercontent.com/14998558/75631149-1011d100-5bb6-11ea-9547-c2ff51f686a0.png)

**Comment by rodri-dot-git** [comment]
Gracias profe, checo esos detalles de ortografía para la siguiente revisión.
