### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by grupohernandezalba** [rodri-dot-git/sistemas-geo#3]
Excelente @rodri-dot-git  vi que implementaste la opción de Editar, quizas si ocultas el boton de guardar y que se muestre hasta que le des clic en editar quedaría mejor y mas claro para el usuario.

![Captura de Pantalla 2020-03-12 a la(s) 21 37 35](https://user-images.githubusercontent.com/14998558/76587553-e86e1300-64a9-11ea-9598-cd595996a06f.png)

**Comment by rodri-dot-git** [comment]
@grupohernandezalba buena recomendación profe ya hice los cambios!
